require('pry')
require('PG')
require_relative('../models/customer.rb')
require_relative('../models/film.rb')
require_relative('../models/ticket.rb')

Ticket.delete_all()
Film.delete_all()
Customer.delete_all()

customer1 = Customer.new('customer_name' => 'Martin Reid', 'customer_funds' => 100)
customer1.save()
customer2 = Customer.new('customer_name' => 'Joe Bloggs', 'customer_funds' => 100)
customer2.save()
customer3 = Customer.new('customer_name' => 'Sam Snead', 'customer_funds' => 100)
customer3.save()
customer4 = Customer.new('customer_name' => 'Julia Friend', 'customer_funds' => 100)
customer4.save()

film1 = Film.new('film_title' => 'Alien Covenant', 'film_price' => 12)
film1.save()
film2 = Film.new('film_title' => 'Interstellar', 'film_price' => 10)
film2.save()
film3 = Film.new('film_title' => 'Blade Runner', 'film_price' => 10)
film3.save()
film4 = Film.new('film_title' => 'Blade Runner 2049', 'film_price' => 15)
film4.save()
film5 = Film.new('film_title' => 'The Accountant', 'film_price' => 10)
film5.save()
film6 = Film.new('film_title' => 'Dunkirk', 'film_price' => 10)
film6.save()
film7 = Film.new('film_title' => 'Inception', 'film_price' => 5)
film7.save()
film8 = Film.new('film_title' => 'The Prestige', 'film_price' => 5)
film8.save()

ticket1 = Ticket.new('customer_id' => customer1.id, 'film_id' => film1.id)
ticket1.save()
ticket2 = Ticket.new('customer_id' => customer1.id, 'film_id' => film2.id)
ticket2.save()
ticket3 = Ticket.new('customer_id' => customer1.id, 'film_id' => film4.id)
ticket3.save()
ticket4 = Ticket.new('customer_id' => customer1.id, 'film_id' => film6.id)
ticket4.save()
ticket5 = Ticket.new('customer_id' => customer2.id, 'film_id' => film1.id)
ticket5.save()
ticket6 = Ticket.new('customer_id' => customer2.id, 'film_id' => film3.id)
ticket6.save()
ticket7 = Ticket.new('customer_id' => customer2.id, 'film_id' => film4.id)
ticket7.save()
ticket8 = Ticket.new('customer_id' => customer2.id, 'film_id' => film8.id)
ticket8.save()
ticket9 = Ticket.new('customer_id' => customer3.id, 'film_id' => film2.id)
ticket9.save()
ticket10 = Ticket.new('customer_id' => customer3.id, 'film_id' => film3.id)
ticket10.save()
ticket11 = Ticket.new('customer_id' => customer3.id, 'film_id' => film5.id)
ticket11.save()
ticket12 = Ticket.new('customer_id' => customer3.id, 'film_id' => film7.id)
ticket12.save()
ticket13 = Ticket.new('customer_id' => customer4.id, 'film_id' => film1.id)
ticket13.save()
ticket14 = Ticket.new('customer_id' => customer4.id, 'film_id' => film5.id)
ticket14.save()
ticket15 = Ticket.new('customer_id' => customer4.id, 'film_id' => film6.id)
ticket15.save()
ticket16 = Ticket.new('customer_id' => customer4.id, 'film_id' => film7.id)
ticket16.save()

binding.pry
nil
